const express = require('express')
const Route = express.Router()
// const ruanganRouter = require('../modules/dataPeminjam/dataPeminjam_routes')
const authRouter = require('../modules/auth/auth_routes')
const userRouter = require('../modules/user/user_routes')
// const bookingRuanganRouter = require('../modules/bookingRuangan/bookingRuangan_routes')
// const laporanRuanganRouter = require('../modules/laporanRuangan/laporanRuangan_routes')
// const waitingListRouter = require('../modules/waitingList/waitingList_routes')
// const laporanAktivitas = require('../modules/laporanAktivitas/laporanAktivitas_routes')
const kendaraan = require('../modules/dataSTNK/dataSTNK_routes')
const dataPemegang = require('../modules/dataPemegangKendaraan/dataPemegangKendaraan_routes')
const Pemeliharaan = require('../modules/Pemeliharaan/Pemeliharaan_routes')
const Bengkel = require('../modules/UangBengkel/UangBengkel_routes')

Route.use('/bengkel', Bengkel)
Route.use('/pemeliharaan', Pemeliharaan)
Route.use('/datapemegang', dataPemegang)
Route.use('/stnk', kendaraan)
// Route.use('/waitinglist', waitingListRouter)
// Route.use('/ruangan', ruanganRouter)
// Route.use('/bookingruangan', bookingRuanganRouter)
Route.use('/user', userRouter)
Route.use('/auth', authRouter)
// Route.use('/laporanruangan', laporanRuanganRouter)
// Route.use('/laporanaktivitas', laporanAktivitas)
module.exports = Route
